version: '3.3'

services:
   web:
     image: hasmukhlalpatel/dotnetdockerdemo:latest
     ports:
       - "8080:80"
     restart: always
     networks:
      - webnet

   webapi:
     depends_on:
       - mongo
     image: hasmukhlalpatel/dotnetdockerwebapi:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       MONGO_DB_HOST: mongo
       MONGO_DB_USER: test
       MONGO_DB_PASSWORD: test
     networks:
      - webnet

   mongo:
     image: mongo:latest
     restart: always
     environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssword
     networks:
      - webnet
      
volumes:
    db_data:
networks:
    webnet:
